/*
 * macro.h - macro definition and expansion.
 *
 * This is a preprocessing step over raw source *text*, run before
 * split_line() (lineparser.h) ever sees a line -- it knows nothing
 * about labels, opcodes, or addressing modes, only about
 * ".macro"/".endmacro" blocks, parameter substitution, and recognizing
 * when a line invokes a macro name instead of a real mnemonic. See
 * fileio.c for where this plugs into the pipeline: it sits directly
 * between "read a raw line from the file" and "hand a line to
 * split_line()".
 *
 * Syntax:
 *     .macro NAME param1, param2
 *             ; body, referencing \param1, \param2
 *     .endmacro
 * invoked like a pseudo-instruction:
 *     NAME arg1, arg2
 *
 * Deliberate limitations (documented in c64asm-reference.md, not
 * oversights):
 *   - Macros must be defined before they're used -- there's no separate
 *     pre-scan of the whole file for macro definitions first, so this
 *     stays a simple single-pass expansion.
 *   - No automatic local-label mangling: a label defined inside a macro
 *     body will collide with "Symbol already defined" if that macro is
 *     invoked more than once. The recommended pattern is to pass a
 *     unique suffix in as a parameter and use it in the label name
 *     (e.g. "loop\suffix:" / "bne loop\suffix"), so each expansion's
 *     labels are distinct by construction.
 *   - A macro invocation can't share a line with a label ("foo: SOME_MACRO
 *     x" doesn't work) -- put the label on its own line above instead.
 *   - Macro arguments are split the same comma/paren/quote-aware way
 *     directive argument lists are (see split_args() in strutils.h) --
 *     which means a full indexed operand like "(ptr),Y" can't be passed
 *     as a single argument, since its comma sits outside any
 *     parentheses. Parameterize the base address and bake the ",Y" into
 *     the macro body instead.
 *   - Nested *definitions* (a ".macro" inside another macro's body) are
 *     rejected outright. Nested *invocations* (one macro calling
 *     another) are fine, up to MAX_MACRO_EXPANSION_DEPTH deep, which
 *     exists purely to turn "a macro that (directly or indirectly)
 *     invokes itself" into a clear error instead of a hang.
 */

#ifndef C64ASM_MACRO_H
#define C64ASM_MACRO_H

/*
 * Feeds one raw source line through macro processing.
 *
 * - If a ".macro"/".endmacro" definition is in progress, absorbs this
 *   line as part of its body (or ends the definition, for ".endmacro").
 * - If the line invokes an already-defined macro, expands it: each body
 *   line has its parameters substituted, then is recursively fed back
 *   through this same function -- which is what makes a macro invoking
 *   another macro, or a macro invoking an ordinary instruction, both
 *   "just work" without any special-casing.
 * - Otherwise, this is an ordinary line: split_line() (lineparser.h) is
 *   called on it and the result appended to g_lines, exactly as
 *   fileio.c's load_source() used to do directly before macro support
 *   existed.
 *
 * raw_line: one line of source, as fgets() would hand it over.
 * line_no:  1-based line number. Every line generated by expanding one
 *           macro invocation is attributed to the *invocation's* line
 *           number, not a line within the macro's own definition --
 *           simpler than tracking definition-relative line numbers, at
 *           the cost of an error inside a macro body pointing you to
 *           where it was *called* rather than the exact body line. For
 *           a hobbyist assembler's macro bodies (typically a handful of
 *           lines), that's a reasonable trade.
 */
void macro_process_line(const char *raw_line, int line_no);

#endif
